# Matugen utility functions for Material You theme generation
#
# Usage:
#   lib.desktop.matugen.mkBase16Template { polarity = "dark"; }
#   lib.desktop.matugen.mkDerivation { pkgs, matugenPackage, image, polarity, scheme, templates }
#
{ lib }:
{
  matugen = {
    # Generate a base16 template YAML for Material You → base16 color mapping
    mkBase16Template =
      { polarity }:
      ''
        system: base16
        slug: matugen-material
        name: Matugen Material
        author: Generated by Matugen
        variant: ${polarity}
        palette:
          base00: "{{colors.background.default.hex}}"
          base01: "{{colors.surface_container_lowest.default.hex}}"
          base02: "{{colors.surface_container_low.default.hex}}"
          base03: "{{colors.outline_variant.default.hex}}"
          base04: "{{colors.on_surface_variant.default.hex}}"
          base05: "{{colors.on_surface.default.hex}}"
          base06: "{{colors.inverse_on_surface.default.hex}}"
          base07: "{{colors.surface_bright.default.hex}}"
          base08: "{{colors.error.default.hex}}"
          base09: "{{colors.tertiary.default.hex}}"
          base0A: "{{colors.secondary.default.hex}}"
          base0B: "{{colors.primary.default.hex}}"
          base0C: "{{colors.tertiary_container.default.hex}}"
          base0D: "{{colors.primary_container.default.hex}}"
          base0E: "{{colors.secondary_container.default.hex}}"
          base0F: "{{colors.error_container.default.hex}}"
      '';

    # Generate TOML configuration for matugen templates
    # Takes an attrset of { name = { template, path }; } and produces TOML entries
    mkTemplateConfig =
      templates:
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: tmpl: ''
          [templates.${name}]
          input_path = "${tmpl.template}"
          output_path = "$out/${tmpl.path}"
        '') templates
      );

    # Build a matugen derivation that generates all templates
    #
    # Arguments:
    #   pkgs          - nixpkgs package set
    #   matugenPackage - the matugen package to use
    #   image         - path to wallpaper image
    #   polarity      - "light" or "dark"
    #   scheme        - matugen scheme type (e.g., "scheme-expressive")
    #   templates     - attrset of { name = { template, path }; }
    #
    # Returns: derivation with generated files
    mkDerivation =
      {
        pkgs,
        matugenPackage,
        image,
        polarity,
        scheme,
        templates,
      }:
      let
        templateConfig = lib.desktop.matugen.mkTemplateConfig templates;
      in
      pkgs.runCommand "matugen-generated"
        {
          nativeBuildInputs = [ matugenPackage ];
        }
        ''
          mkdir -p $out

          # Create matugen config
          cat > config.toml << EOF
          [config]

          ${templateConfig}
          EOF

          # Generate all templates
          matugen image ${image} \
            --type ${scheme} \
            --mode ${polarity} \
            --config config.toml
        '';
  };
}
