# Matugen utility functions for Material You theme generation
#
# Provides utilities for generating base16-compatible color schemes from
# wallpaper images using matugen (Material You color generation).
#
# Usage:
#   lib.desktop.matugen.mkBase16Template { polarity = "dark"; }
#   lib.desktop.matugen.mkDerivation { pkgs, matugenPackage, image, polarity, scheme, templates }
#
{ lib }:

{
  matugen = {
    # Generate a base16 template YAML for Material You color mapping
    #
    # Creates a YAML template that maps Material You color tokens to the
    # standard base16 color scheme format for use with theme generators.
    #
    # Arguments:
    #   polarity: Theme variant - "light" or "dark"
    #
    # Returns: String containing YAML template with matugen color placeholders
    #
    # Usage:
    #   lib.desktop.matugen.mkBase16Template { polarity = "dark"; }
    #
    mkBase16Template =
      { polarity }:
      ''
        system: base16
        slug: matugen-material
        name: Matugen Material
        author: Generated by Matugen
        variant: ${polarity}
        palette:
          base00: "{{colors.background.default.hex}}"
          base01: "{{colors.surface_container_lowest.default.hex}}"
          base02: "{{colors.surface_container_low.default.hex}}"
          base03: "{{colors.outline_variant.default.hex}}"
          base04: "{{colors.on_surface_variant.default.hex}}"
          base05: "{{colors.on_surface.default.hex}}"
          base06: "{{colors.inverse_on_surface.default.hex}}"
          base07: "{{colors.surface_bright.default.hex}}"
          base08: "{{colors.error.default.hex}}"
          base09: "{{colors.tertiary.default.hex}}"
          base0A: "{{colors.secondary.default.hex}}"
          base0B: "{{colors.primary.default.hex}}"
          base0C: "{{colors.tertiary_container.default.hex}}"
          base0D: "{{colors.primary_container.default.hex}}"
          base0E: "{{colors.secondary_container.default.hex}}"
          base0F: "{{colors.error_container.default.hex}}"
      '';

    # Build a matugen derivation that generates themed files
    #
    # Creates a Nix derivation that runs matugen to generate all specified
    # template files from a wallpaper image using Material You color extraction.
    #
    # Arguments:
    #   pkgs: Nixpkgs package set
    #   matugenPackage: The matugen package to use for generation
    #   image: Path to wallpaper image for color extraction
    #   polarity: Theme variant - "light" or "dark"
    #   scheme: Matugen scheme type (e.g., "scheme-expressive", "scheme-tonal-spot")
    #   templates: Attrset of { name = { template, path }; } defining output files
    #
    # Returns: Derivation containing generated files at specified paths
    #
    # Usage:
    #   lib.desktop.matugen.mkDerivation {
    #     inherit pkgs;
    #     matugenPackage = pkgs.matugen;
    #     image = ./wallpaper.png;
    #     polarity = "dark";
    #     scheme = "scheme-expressive";
    #     templates = {
    #       colors = { template = ./colors.yaml; path = "colors.yaml"; };
    #     };
    #   }
    #
    mkDerivation =
      {
        pkgs,
        matugenPackage,
        image,
        polarity,
        scheme,
        templates,
      }:
      let
        templateConfig = lib.desktop.matugen.mkTemplateConfig templates;
      in
      pkgs.runCommand "matugen-generated"
        {
          nativeBuildInputs = [ matugenPackage ];
        }
        ''
          mkdir -p $out

          # Create matugen config
          cat > config.toml << EOF
          [config]

          ${templateConfig}
          EOF

          # Generate all templates
          matugen image ${image} \
            --type ${scheme} \
            --mode ${polarity} \
            --config config.toml
        '';

    # Generate TOML configuration for matugen templates
    #
    # Transforms a Nix attrset of template definitions into TOML format
    # suitable for matugen's configuration file.
    #
    # Arguments:
    #   templates: Attrset of { name = { template, path }; }
    #     - template: Path to the input template file
    #     - path: Output path relative to derivation root
    #
    # Returns: String containing TOML template configuration sections
    #
    # Usage:
    #   lib.desktop.matugen.mkTemplateConfig {
    #     colors = { template = ./colors.yaml; path = "colors.yaml"; };
    #     theme = { template = ./theme.css; path = "theme.css"; };
    #   }
    #
    mkTemplateConfig =
      templates:
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: tmpl: ''
          [templates.${name}]
          input_path = "${tmpl.template}"
          output_path = "$out/${tmpl.path}"
        '') templates
      );
  };
}
